version: 0.2
###
# This build project exports any variables needed for later stages and actions,
# builds and packages the lambdas and builds the template configs used to launch
# the CloudFormation templates

env:
  shell: bash
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  exported-variables:
    - CODEBUILD_BUILD_NUMBER
    - APP_STACK_FILE

phases:

  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Running on $(lsb_release -d | cut -f2)
      - echo aws-cli version $(aws --version)
    finally:
      - #echo This always runs even if the update or install command fails
      - #notify Slack on failure


  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo source branch is $SRC_BRANCH
      - echo clean branch is $CLEAN_BRANCH
      - echo Environment is $ENVIRONMENT
      - echo generating environment vars...
      - cicd/pipeline/gen_env_vars.py --env $ENVIRONMENT --clean-branch $CLEAN_BRANCH --conf config.ini > env.txt
      - echo loading config..
      - set -a ; source env.txt ; set +a
    finally:
      - #echo This always runs
      - #notify Slack on failure

  build:
    commands:
      - echo Entered the build phase...
      # docs portal pkce template config
      - echo Generating the docs portal pkce stack template config
      - cicd/pipeline/gen_template_config.py  --template cicd/pipeline/docs_portal_pkce_template_config.j2 > cicd/app/docs_portal_pkce_template_config.json
    finally:
      - #echo This always runs
      - #notify Slack on failure


  post_build:
    commands:
      - #echo Entered the post_build phase...
      - #notify Slack

artifacts:
  files:
    - cicd/app/$APP_STACK_FILE
    - cicd/app/docs_portal_pkce_template_config.json
  name: BuildTemplateConfigArtifact
  discard-paths: no
