AWSTemplateFormatVersion: "2010-09-09"
Description: Api Docs portal PKCE token generator

Parameters:
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pBucketName:
    Type: String
    Description: The bucket name for the site
  pBucketPath:
    Type: String
    Description: Optional path that the files are stored under in the bucket
  pCleanBranch:
    Type: String
    Description: A cleaned version of the code branch name
    Default: development
  pHostedZone:
    Type: String
    Description: The hosted zone the site is accessed under
  pSubDomain:
    Type: String
    Description: The subdomain the site is accessed on
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used 

Conditions:
  IsDev: !Equals 
    - !Ref pEnvironment
    - development

Resources:
  
  ApiTokensPortalBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pBucketName}
      LifecycleConfiguration:
        Rules:
          - Id: delete incomplete uploads
            AbortIncompleteMultipartUpload:
               DaysAfterInitiation: 1
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: component
          Value: website
        - Key: Name
          Value: !Sub api-tokens-portal-${pEnvironment}

  ApiTokensPortalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ApiTokensPortalBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join [ '', ['arn:aws:s3:::', !Ref ApiTokensPortalBucket ,'/*' ]]
            Principal: 
              AWS: !Join [ '', [ 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ', !Ref ApiTokensPortalCloudFrontOia ]]

  ApiTokensPortalDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${pSubDomain}.${pHostedZone}"
      Comment: !Sub api tokens portal domain name for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiTokensPortalCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub "${pHostedZone}."

  ApiTokensPortalCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn: ApiTokensPortalBucket
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${pSubDomain}.${pHostedZone}"
        Comment: !Sub api tokens portal site ${pEnvironment}
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          CachePolicyId: !Ref ApiTokensPortalCachePolicy 
          Compress: true
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt ApiTokensPortalCloudFrontFunction.FunctionMetadata.FunctionARN
          TargetOriginId: api-tokens-portal-s3
          ViewerProtocolPolicy: redirect-to-https 
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub "${pBucketName}.s3.${AWS::Region}.amazonaws.com"
            Id: api-tokens-portal-s3
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref ApiTokensPortalCloudFrontOia ]]
            OriginPath: !Sub "/${pBucketPath}"
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: component
          Value: cdn

  ApiTokensPortalCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties: 
      CachePolicyConfig: 
        Comment: !Sub CF Cache Policy for the api tokens portal site ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
                - "ApiTokensPortal-cache-Policy-${ResourceName}"
                - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
        ParametersInCacheKeyAndForwardedToOrigin: 
          CookiesConfig: 
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: whitelist
            QueryStrings: 
              - cb

  ApiTokensPortalCloudFrontOia:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for the api tokens portal ${pEnvironment}

  ApiTokensPortalCloudFrontFunction:
    Type: AWS::CloudFront::Function
    Properties: 
      AutoPublish: true
      FunctionCode: |
                      function handler(event) {
                        var request = event.request;

                        if (!request.uri.includes('.')) {
                          request.uri = "/index.html";
                          request.querystring = {}
                        }

                        return request;
                      }
      FunctionConfig: 
        Comment: Rewrite non static requests to index.html for the React SPA
        Runtime: cloudfront-js-1.0
      Name: !Sub
              - "Api-tokens-portal-react-SPA-rewrite-${ResourceName}"
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

Outputs:
  ApiTokensPortalBucketName:
    Value: !Ref ApiTokensPortalBucket
  ApiTokensPortalBucketArn:
    Value: !GetAtt ApiTokensPortalBucket.Arn
  ApiTokensPortalCloudFrontDistributionId:
    Value: !Ref ApiTokensPortalCloudFrontDistro